name: Pull Requests Check

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build project
        id: build
        run: |
          uname -a
          cp -r third-party /tmp/third-party
          cp compile.sh /tmp/
          cd /tmp
          chmod 755 compile.sh
          ./compile.sh > /tmp/elog 2>&1  # Capture stderr as well
          find /tmp/third-party/ >> /tmp/elog
          echo "::set-output name=res::$(uname -a)"
          echo "::set-output name=elog::$(cat /tmp/elog)"

      - name: Upload build log
        uses: actions/upload-artifact@v3
        with:
          name: build-log-${{ matrix.os }}
          path: /tmp/elog

      - name: Build Summary
        run: |
          echo "# Arch" >> $GITHUB_STEP_SUMMARY
          echo "\`${{ steps.build.outputs.res }}\`" >> $GITHUB_STEP_SUMMARY
          echo "# Build Result" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.build.outputs.elog }}" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
